# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  # PR for security updates only
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      security-updates:
        patterns:
          - "*"
        update-types:
          - "security"
    commit-message:
      prefix: "chore(security): "
      prefix-development: "chore(security-dev): "
    ignore:
      - dependency-type: "all"
        update-types: ["version-update:semver-major", "version-update:semver-minor", "version-update:semver-patch"]

  # PR for major version updates
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"
    groups:
      major-updates:
        patterns:
          - "*"
        update-types:
          - "version-update:semver-major"
    commit-message:
      prefix: "chore(deps): "
      prefix-development: "chore(deps-dev): "
    ignore:
      - dependency-type: "all"
        update-types: ["version-update:semver-minor", "version-update:semver-patch", "security"]

  # PR for minor and patch version updates
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"
    open-pull-requests-limit: 1
    groups:
      minor-and-patch-updates:
        patterns:
          - "*"
        update-types:
          - "version-update:semver-minor"
          - "version-update:semver-patch"
    commit-message:
      prefix: "chore(deps): "
      prefix-development: "chore(deps-dev): "
    ignore:
      - dependency-type: "all"
        update-types: ["version-update:semver-major", "security"]